# https://circleci.com/developer/orbs/orb/circleci/node
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  my-app:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test:percy

workflows:
  version: 2
  build:
    jobs:
      - my-app
