version: 2.1

orbs:
  node: circleci/node@4.1
  percy: percy/agent@0.28.6

jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test:percy

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
      - percy/finalize_all:
          requires:
            - build-and-test
