version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages
      - run: yarn install
      - run: yarn build
      - run: yarn test:percy

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
      - percy/finalize_all:
          requires:
            - build-and-test
