# https://circleci.com/developer/orbs/orb/circleci/node
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  my-app:
    docker:
      - image: circleci/node:latest-browsers
    # working_directory: ~/repo
    steps:
      - checkout  # checkout the repository
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn build
      # - run: yarn test:percy
      # debug cli
      - run: yarn percy exec -- percy health-check
      - run: yarn percy exec -- curl localhost:3000
      - run: yarn percy snapshot localhost:3000 # run Percy

workflows:
  version: 2
  build:
    jobs:
      - my-app
